
function get_drive_name() {
  dir_name=`find /dev/mapper -maxdepth 1 -type l -name '*cl*' -print -quit`
  DRIVE_NAME=`grep -oP '(?<=_).*?(?=-)' <<< "$dir_name"`
}

function grow_fs() {
  get_drive_name

  #One time machine setup
  xfsdump -f /tmp/home.dump /home

  umount /home
  lvreduce -L 20G -f /dev/mapper/cl_$DRIVE_NAME-home
  mkfs.xfs -f /dev/mapper/cl_$DRIVE_NAME-home
  lvextend -l +100%FREE /dev/mapper/cl_$DRIVE_NAME-root
  xfs_growfs /dev/mapper/cl_$DRIVE_NAME-root
  mount /dev/mapper/cl_$DRIVE_NAME-home /home
  xfsrestore -f /tmp/home.dump /home
}

function load_libs() {

  option="${1}"
  case $option in
    "control")
            yum clean all && yum update -y  #this is only to make the next call work, DONT remove!
            #One time machine setup
            #install yum libs here
            yum install -y wget \
            unzip \
            epel-release \
            gcc \
            openssl-devel \
            git \
            make \
            python2
    ;;
    "network")
            yum clean all && yum update -y  #this is only to make the next call work, DONT remove!
            #One time machine setup
            #install yum libs here
            yum install -y wget \
            unzip \
            epel-release \
            gcc \
            openssl-devel \
            git \
            make \
            python2
    ;;
    "compute")
            yum clean all && yum update -y  #this is only to make the next call work, DONT remove!
            #One time machine setup
            #install yum libs here
            yum install -y wget \
            unzip \
            epel-release \
            gcc \
            openssl-devel \
            git \
            make \
            python2
    ;;
    "monitoring")
            yum clean all && yum update -y  #this is only to make the next call work, DONT remove!
            #One time machine setup
            #install yum libs here
            yum install -y wget \
            unzip \
            epel-release \
            gcc \
            openssl-devel \
            git \
            make \
            python2
    ;;
    "storage")
            yum clean all && yum update -y  #this is only to make the next call work, DONT remove!
            #One time machine setup
            #install yum libs here
            yum install -y wget \
            unzip \
            epel-release \
            gcc \
            openssl-devel \
            git \
            make \
            python2
    ;;
    "kolla")
          yum install -y wget \
          ruby \
          unzip \
          virt-install \
          qemu-kvm \
          epel-release \
          libffi-devel \
          gcc \
          openssl-devel \
          git \
          python3-devel \
          python38 \
          chrony \
          make \
          python2 \
          gcc-c++ \
          ruby \
          ruby-devel \
          mysql-devel \
          postgresql-devel \
          postgresql-libs \
          sqlite-devel \
          libxslt-devel \
          libxml2-devel \
          patch \
          openssl
    ;;
  esac
}

function use_old_net_names() {
  get_drive_name

  runuser -l root -c  'rm -rf /etc/default/grub'
  runuser -l root -c  'touch /etc/default/grub'
  runuser -l root -c  'chmod 777 /etc/default/grub'

cat > /tmp/grub <<EOF
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL_OUTPUT="console"
GRUB_CMDLINE_LINUX="crashkernel=auto resume=/dev/mapper/cl_$DRIVE_NAME-swap rd.lvm.lv=cl_$DRIVE_NAME/root rd.lvm.lv=cl_$DRIVE_NAME/swap net.ifnames=0"
GRUB_DISABLE_RECOVERY="true"
GRUB_ENABLE_BLSCFG=true
EOF

  runuser -l root -c  'cat /tmp/grub > /etc/default/grub'

  runuser -l root -c  'grub2-mkconfig  -o /boot/grub2/grub.cfg'

  ct=0
  net_names=("192" "224" "256" "161")
  for element in "${net_names[@]}"
  do
    entry="/etc/sysconfig/network-scripts/ifcfg-ens$element"
    if test -f "$entry"; then

        IP=(`awk -F'=' '$1 == "IPADDR" {print $2}' $entry`)
        runuser -l root -c  "touch /etc/sysconfig/network-scripts/ifcfg-eth$ct"

if [[ ! -z "$IP" ]]
then
#static ip addr
cat > /tmp/eth$ct <<EOF
# Generated by parse-kickstart
TYPE="Ethernet"
NAME="eth$ct"
DEVICE="eth$ct"
UUID="5844195f-b0d7-4d15-9442-87d1340cca2$ct"
ONBOOT="yes"
IPV6INIT="yes"
IPV6_AUTOCONF="yes"
IPADDR=$IP
BOOTPROTO="static"
EOF
else
#dynamic ip addr (use DHCP)
cat > /tmp/eth$ct <<EOF
# Generated by parse-kickstart
TYPE="Ethernet"
NAME="eth$ct"
DEVICE="eth$ct"
UUID="5844195f-b0d7-4d15-9442-87d1340cca2$ct"
ONBOOT="yes"
IPV6INIT="yes"
IPV6_AUTOCONF="yes"
BOOTPROTO="dhcp"
EOF
fi

    runuser -l root -c  "cat /tmp/eth$ct > /etc/sysconfig/network-scripts/ifcfg-eth$ct"

    runuser -l root -c  "rm -rf $entry"
    ((ct++))
    fi

  done

}

function add_stack_user() {
  runuser -l root -c  'useradd -s /bin/bash -d /opt/stack -m stack'
  runuser -l root -c  'echo "stack ALL=(ALL) NOPASSWD: ALL" | tee /etc/sudoers.d/stack'
  runuser -l root -c  'su - stack'
}

function prep_next_script() {
  systemctl start cockpit.socket
  systemctl enable --now cockpit.socket

  ## Prep OpenStack install
  rm -rf /etc/rc.d/rc.local
  curl -o /etc/rc.d/rc.local https://raw.githubusercontent.com/mephmanx/openstack-scripts/master/$1.sh
  chmod +x /etc/rc.d/rc.local
}