
function get_drive_name() {
  dir_name=`find /dev/mapper -maxdepth 1 -type l -name '*cl*' -print -quit`
  DRIVE_NAME=`grep -oP '(?<=_).*?(?=-)' <<< "$dir_name"`
}

function grow_fs() {
  get_drive_name

  #One time machine setup
  xfsdump -f /tmp/home.dump /home

  umount /home
  lvreduce -L 20G -f /dev/mapper/cl_$DRIVE_NAME-home
  mkfs.xfs -f /dev/mapper/cl_$DRIVE_NAME-home
  lvextend -l +100%FREE /dev/mapper/cl_$DRIVE_NAME-root
  xfs_growfs /dev/mapper/cl_$DRIVE_NAME-root
  mount /dev/mapper/cl_$DRIVE_NAME-home /home
  xfsrestore -f /tmp/home.dump /home
}

function load_libs() {
  option="${1}"
  case "${option}" in
    "control")
            yum clean all && yum update -y  #this is only to make the next call work, DONT remove!
            #One time machine setup
            #install yum libs here
            yum install -y wget \
            unzip \
            epel-release \
            gcc \
            openssl-devel \
            git \
            make
    ;;
    "network")
            yum clean all && yum update -y  #this is only to make the next call work, DONT remove!
            #One time machine setup
            #install yum libs here
            yum install -y wget \
            unzip \
            epel-release \
            gcc \
            openssl-devel \
            git \
            make
    ;;
    "compute")
            yum clean all && yum update -y  #this is only to make the next call work, DONT remove!
            #One time machine setup
            #install yum libs here
            yum install -y wget \
            unzip \
            epel-release \
            gcc \
            openssl-devel \
            git \
            make
    ;;
    "monitoring")
            yum clean all && yum update -y  #this is only to make the next call work, DONT remove!
            #One time machine setup
            #install yum libs here
            yum install -y wget \
            unzip \
            epel-release \
            gcc \
            openssl-devel \
            git \
            make
    ;;
    "storage")
            yum clean all && yum update -y  #this is only to make the next call work, DONT remove!
            #One time machine setup
            #install yum libs here
            yum install -y wget \
            unzip \
            epel-release \
            gcc \
            openssl-devel \
            git \
            make
    ;;
    "kolla")
          yum install -y wget \
          ruby \
          unzip \
          virt-install \
          qemu-kvm \
          epel-release \
          libffi-devel \
          gcc \
          openssl-devel \
          git \
          python3-devel \
          python38 \
          chrony \
          make \
          python2 \
          gcc-c++ \
          ruby \
          ruby-devel \
          mysql-devel \
          postgresql-devel \
          postgresql-libs \
          sqlite-devel \
          libxslt-devel \
          libxml2-devel \
          patch \
          openssl
    ;;
  esac
}

function use_old_net_names() {
  get_drive_name

  runuser -l root -c  'rm -rf /etc/default/grub'
  runuser -l root -c  'touch /etc/default/grub'
  runuser -l root -c  'chmod 777 /etc/default/grub'

cat > /tmp/grub <<EOF
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL_OUTPUT="console"
GRUB_CMDLINE_LINUX="crashkernel=auto resume=/dev/mapper/cl_$DRIVE_NAME-swap rd.lvm.lv=cl_$DRIVE_NAME/root rd.lvm.lv=cl_$DRIVE_NAME/swap net.ifnames=0"
GRUB_DISABLE_RECOVERY="true"
GRUB_ENABLE_BLSCFG=true
EOF

  runuser -l root -c  'cat /tmp/grub > /etc/default/grub'
  runuser -l root -c  'grub2-mkconfig  -o /boot/grub2/grub.cfg'
  ct=0
  # Use no more than 3 NIC cards per VM until ordering is figured out!
  # The next NIC name in the list is 161 and it throws off all NIC cards
  net_names=("192" "224" "256")

  ###################
  for element in "${net_names[@]}"
  do
    entry="/etc/sysconfig/network-scripts/ifcfg-ens$element"
    if test -f "$entry"; then
      IP=(`awk -F'=' '$1 == "IPADDR" {print $2}' $entry`)
      GATEWAY=(`awk -F'=' '$1 == "GATEWAY" {print $2}' $entry`)
      DNS1=(`awk -F'=' '$1 == "DNS1" {print $2}' $entry`)
      NETMASK=(`awk -F'=' '$1 == "NETMASK" {print $2}' $entry`)
      runuser -l root -c  "touch /etc/sysconfig/network-scripts/ifcfg-eth$ct"

if [[ ! -z "$IP" ]]
then
#static ip addr
cat > /tmp/eth$ct <<EOF
# Generated by parse-kickstart
TYPE="Ethernet"
NAME="eth$ct"
DEVICE="eth$ct"
UUID="5844195f-b0d7-4d15-9442-87d1340cca2$ct"
ONBOOT="yes"
IPADDR=$IP
BOOTPROTO="static"
GATEWAY=$GATEWAY
DNS1=$DNS1
NETMASK=$NETMASK
NM_CONTROLLED="no"
EOF
else
#dynamic ip addr (use DHCP)
cat > /tmp/eth$ct <<EOF
# Generated by parse-kickstart
TYPE="Ethernet"
NAME="eth$ct"
DEVICE="eth$ct"
UUID="5844195f-b0d7-4d15-9442-87d1340cca2$ct"
ONBOOT="yes"
BOOTPROTO="dhcp"
NM_CONTROLLED="no"
EOF
fi

      runuser -l root -c  "cat /tmp/eth$ct > /etc/sysconfig/network-scripts/ifcfg-eth$ct"
      runuser -l root -c  "rm -rf $entry"
      ((ct++))
    fi
  done
}

function add_stack_user() {
  runuser -l root -c  'useradd -s /bin/bash -d /opt/stack -m stack'
  runuser -l root -c  'echo "stack ALL=(ALL) NOPASSWD: ALL" | tee /etc/sudoers.d/stack'
  runuser -l root -c  'su - stack'
}

function prep_next_script() {
  systemctl start cockpit.socket
  systemctl enable --now cockpit.socket

  ## Prep OpenStack install
  rm -rf /etc/rc.d/rc.local
  curl -o /etc/rc.d/rc.local -H "Authorization: Bearer $GITHUB_TOKEN" https://raw.githubusercontent.com/mephmanx/openstack-scripts/master/$1.sh
  chmod +x /etc/rc.d/rc.local
}

function common_second_boot_setup() {

  exec 1>/tmp/openstack-install.log 2>&1 # send stdout and stderr from rc.local to a log file
  set -x                             # tell sh to display commands before execution

  yum clean all && yum update -y  #this is only to make the next call work, DONT remove!

  runuser -l root -c  "yum install -y https://$GITHUB_TOKEN@raw.githubusercontent.com/mephmanx/cloud-libs/master/docker-ce-cli-18.09.9-3.el7.x86_64.rpm"
  sleep 5
  runuser -l root -c  "yum install -y https://$GITHUB_TOKEN@raw.githubusercontent.com/mephmanx/cloud-libs/master/docker-ce-18.09.9-3.el7.x86_64.rpm"
  sleep 5

  systemctl restart docker
  docker login -u $PORTUS_USERNAME -p $PORTUS_PASSWORD $MACHINE_FQDN:$REGISTRY_PORT

  mkdir /root/.ssh
  cp /tmp/openstack-setup.key.pub /root/.ssh/authorized_keys
  mv /tmp/openstack-setup.key.pub /root/.ssh/id_rsa.pub
  mv /tmp/openstack-setup.key /root/.ssh/id_rsa
  chmod 600 /root/.ssh/id_rsa
  chmod 600 /root/.ssh/authorized_keys

  systemctl stop firewalld
  systemctl mask firewalld
}