#!/bin/bash
# chkconfig: 2345 20 80
# description: Description comes here....
# ALWAYS have content in functions otherwise you get syntax errors!

# Source function library.
. /etc/init.d/functions

start() {
# code to start app comes here
# example: daemon program_name &
exec 1>/tmp/start-install.log 2>&1 # send stdout and stderr from rc.local to a log file
set -x                             # tell sh to display commands before execution

#One time machine setup
#install yum libs here


yum install -y yum-utils \
                wget \
                ruby \
                unzip \
                libvirt \
                virt-install \
                qemu-kvm \
                epel-release \
                libffi-devel \
                gcc \
                openssl-devel \
                git \
                python3-devel \
                python38 \
                chrony \
                libvirt-devel \
                libvirt-daemon-kvm \
                libvirt-client \
                make \
                ruby \
                ruby-devel \
                gcc-c++ \
                mysql-devel \
                postgresql-devel \
                nodejs \
                mysql-server

systemctl start cockpit.socket
systemctl enable --now cockpit.socket

dnf upgrade -y
dnf install -y epel-release snapd
systemctl enable --now snapd.socket
firewall-cmd --permanent --add-service=snapd

runuser -l root -c  'rm -rf /etc/default/grub'
runuser -l root -c  'touch /etc/default/grub'
runuser -l root -c  'chmod 777 /etc/default/grub'
cat > /tmp/grub <<EOF
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL_OUTPUT="console"
GRUB_CMDLINE_LINUX="crashkernel=auto resume=/dev/mapper/cl_cloudsupport-swap rd.lvm.lv=cl_cloudsupport/root rd.lvm.lv=cl_cloudsupport/swap net.ifnames=0 ipv6.disable=1"
GRUB_DISABLE_RECOVERY="true"
GRUB_ENABLE_BLSCFG=true
EOF

runuser -l root -c  'cat /tmp/grub > /etc/default/grub'

runuser -l root -c  'grub2-mkconfig  -o /boot/grub2/grub.cfg'

runuser -l root -c  'rm -rf /etc/sysconfig/network-scripts/ifcfg-ens*'
runuser -l root -c  'touch /etc/sysconfig/network-scripts/ifcfg-eth0'


cat > /tmp/eth0 <<EOF
# Generated by parse-kickstart
TYPE="Ethernet"
DEVICE="eth0"
UUID="5844195f-b0d7-4d15-9442-87d1340cca24"
ONBOOT="yes"
BOOTPROTO="dhcp"
IPV6INIT="no"
IPV6_AUTOCONF="no"
NM_CONTROLLED="no"
EOF

runuser -l root -c  'cat /tmp/eth0 > /etc/sysconfig/network-scripts/ifcfg-eth0'

## Prep OpenStack install
rm -rf /etc/rc.d/rc.local
curl -o /etc/rc.d/rc.local https://raw.githubusercontent.com/mephmanx/openstack-scripts/master/cloudsupport.sh
chmod +x /etc/rc.d/rc.local

########################
#remove this script so it only runs once on machine start
rm -rf /etc/init.d/vmware-centos8.sh
reboot

}

stop() {
    # code to stop app comes here 
    # example: killproc program_name
    /bin/true
}

case "$1" in 
    start)
       start
       ;;
    stop)
        /bin/true
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
        /bin/true
       # code to check status of app comes here 
       # example: status program_name
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 
